const FETCH_USERS_REQUESTED = "FETCH_USERS_REQUESTED"
const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
const FETCH_USERS_ERROR = "FETCH_USERS_ERROR"

module.exports = {
    FETCH_USERS_REQUESTED,
    FETCH_USERS_SUCCESS,
    FETCH_USERS_ERROR,
}
